p8105_hw2_lr3257
================
Leonor Rui
2024-09-30

# Homework 2

## Problem 1

``` r
### read data file
NYC_df = 
  read_csv("data/NYCsubway.csv",  na = c("NA", "", "."), show_col_types = FALSE) |>
  janitor::clean_names() |>
  mutate(
    entry = ifelse(entry == "YES", TRUE, FALSE)
    )
```

### Description:

There are 32 variables contained in this dataset: division (character),
line (character), station_name (character), station_latitude (double),
station_longtitude (double), route 1-7 (character), route 8-11 (double),
entrance_type (character), entry (character), exit_only (character),
vending (character), staffing (character), staff_hours (character), ada
(logical), ada_notes (character), free_crossover (logical),
north_south_street (character), east_west_street (character), corner
(character), entrance_latitude (double), entrance_longitude (double),
station_location (character), entrance_location (character).

So far, I have used the janitor::clean_names() function for some basic
cleanings about the column names, including converting all column names
to lowercase, replacing spaces and special characters with underscores,
etc. I have also defined the “NA”, “,”, and “.” values in the dataset to
be na for the convenience of later data analysis.

The dimension of the dataset now is 1868 rows x 32 columns. Despite I
have changed the entry variable from character to logical type, the
dataset is still not tidy, as there are many more character variables
that could be turned into logical variables, and there are many NA data
in it that may interfere further data analysis.

- How many distinct stations are there?

``` r
distinct(NYC_df, line, station_name)
```

    ## # A tibble: 465 × 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # ℹ 455 more rows

There are 465 distinct stations.

- How many stations are ADA compliant?

``` r
filter(NYC_df, ada == TRUE)
```

    ## # A tibble: 468 × 32
    ##    division line   station_name station_latitude station_longitude route1 route2
    ##    <chr>    <chr>  <chr>                   <dbl>             <dbl> <chr>  <chr> 
    ##  1 BMT      4 Ave… Atlantic Av…             40.7             -74.0 B      Q     
    ##  2 BMT      4 Ave… DeKalb Av                40.7             -74.0 B      Q     
    ##  3 BMT      4 Ave… DeKalb Av                40.7             -74.0 B      Q     
    ##  4 BMT      4 Ave… DeKalb Av                40.7             -74.0 B      Q     
    ##  5 BMT      4 Ave… DeKalb Av                40.7             -74.0 B      Q     
    ##  6 BMT      4 Ave… DeKalb Av                40.7             -74.0 B      Q     
    ##  7 BMT      4 Ave… DeKalb Av                40.7             -74.0 B      Q     
    ##  8 BMT      4 Ave… Pacific St               40.7             -74.0 B      Q     
    ##  9 BMT      4 Ave… Pacific St               40.7             -74.0 B      Q     
    ## 10 IRT      42nd … Grand Centr…             40.8             -74.0 GS     4     
    ## # ℹ 458 more rows
    ## # ℹ 25 more variables: route3 <chr>, route4 <chr>, route5 <chr>, route6 <chr>,
    ## #   route7 <chr>, route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <lgl>, exit_only <chr>, vending <chr>,
    ## #   staffing <chr>, staff_hours <chr>, ada <lgl>, ada_notes <chr>,
    ## #   free_crossover <lgl>, north_south_street <chr>, east_west_street <chr>,
    ## #   corner <chr>, entrance_latitude <dbl>, entrance_longitude <dbl>, …

468 stations are ADA compliant.

- What proportion of station entrances / exits without vending allow
  entrance?

``` r
vending_df = filter(NYC_df, vending == "NO")
vending_entry_df = filter(vending_df, entry == "TRUE")
nrow(vending_entry_df)/nrow(vending_df)
```

    ## [1] 0.3770492

About 37.7% of stations without vending allow entrance.

- Reformat data so that route number and route name are distinct
  variables. How many distinct stations serve the A train? Of the
  stations that serve the A train, how many are ADA compliant?

``` r
NYC_df = mutate(
    NYC_df,
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)
  ) |>
  pivot_longer(
  cols = route1:route11,
  names_to = "route_number",
  values_to = "route_name",
  names_prefix = "route") |>
  drop_na(route_name)
print(NYC_df)
```

    ## # A tibble: 4,270 × 23
    ##    division line   station_name station_latitude station_longitude entrance_type
    ##    <chr>    <chr>  <chr>                   <dbl>             <dbl> <chr>        
    ##  1 BMT      4 Ave… 25th St                  40.7             -74.0 Stair        
    ##  2 BMT      4 Ave… 25th St                  40.7             -74.0 Stair        
    ##  3 BMT      4 Ave… 36th St                  40.7             -74.0 Stair        
    ##  4 BMT      4 Ave… 36th St                  40.7             -74.0 Stair        
    ##  5 BMT      4 Ave… 36th St                  40.7             -74.0 Stair        
    ##  6 BMT      4 Ave… 36th St                  40.7             -74.0 Stair        
    ##  7 BMT      4 Ave… 36th St                  40.7             -74.0 Stair        
    ##  8 BMT      4 Ave… 36th St                  40.7             -74.0 Stair        
    ##  9 BMT      4 Ave… 45th St                  40.6             -74.0 Stair        
    ## 10 BMT      4 Ave… 45th St                  40.6             -74.0 Stair        
    ## # ℹ 4,260 more rows
    ## # ℹ 17 more variables: entry <lgl>, exit_only <chr>, vending <chr>,
    ## #   staffing <chr>, staff_hours <chr>, ada <lgl>, ada_notes <chr>,
    ## #   free_crossover <lgl>, north_south_street <chr>, east_west_street <chr>,
    ## #   corner <chr>, entrance_latitude <dbl>, entrance_longitude <dbl>,
    ## #   station_location <chr>, entrance_location <chr>, route_number <chr>,
    ## #   route_name <chr>

``` r
A_df = filter(NYC_df, route_name == "A")
A_ada_df = filter(A_df, ada == "TRUE")
A_distinct = distinct(A_df, line, station_name)
A_ada_distinct = distinct(A_ada_df, line, station_name)
```

60 distinct stations serve the A train. Out of these stations, 17
stations are ADA compliant.

## Problem 2

### Mr. Trash Wheel sheet

``` r
Mr_TW = read_excel("data/Trash_wheel.xlsx", sheet = "Mr. Trash Wheel",
                   col_types = c("numeric", "skip", "skip", "skip", "numeric", "numeric", "numeric", "numeric", "numeric","numeric", "numeric", "numeric", "numeric","numeric","skip","skip")) |>
  janitor::clean_names() |>
  mutate(
    sports_balls = as.integer(round(sports_balls))
  ) |>
  slice(1:(n()-1))
print(Mr_TW)
```

    ## # A tibble: 584 × 11
    ##    dumpster weight_tons volume_cubic_yards plastic_bottles polystyrene
    ##       <dbl>       <dbl>              <dbl>           <dbl>       <dbl>
    ##  1        1        4.31                 18            1450        1820
    ##  2        2        2.74                 13            1120        1030
    ##  3        3        3.45                 15            2450        3100
    ##  4        4        3.1                  15            2380        2730
    ##  5        5        4.06                 18             980         870
    ##  6        6        2.71                 13            1430        2140
    ##  7        7        1.91                  8             910        1090
    ##  8        8        3.7                  16            3580        4310
    ##  9        9        2.52                 14            2400        2790
    ## 10       10        3.76                 18            1340        1730
    ## # ℹ 574 more rows
    ## # ℹ 6 more variables: cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

### Professor Trash Wheel

``` r
Prof_TW = read_excel("data/Trash_wheel.xlsx", sheet = "Professor Trash Wheel",
                      col_types = c("numeric", "skip", "skip", "skip", "numeric", "numeric", "numeric", "numeric", "numeric","numeric", "numeric", "numeric", "numeric")) |>
  janitor::clean_names() |>
  slice(1:(n()-1))
print(Prof_TW)
```

    ## # A tibble: 106 × 10
    ##    dumpster weight_tons volume_cubic_yards plastic_bottles polystyrene
    ##       <dbl>       <dbl>              <dbl>           <dbl>       <dbl>
    ##  1        1        1.79                 15            1950        6080
    ##  2        2        1.58                 15            9540       11230
    ##  3        3        2.32                 18            8350        9210
    ##  4        4        3.72                 15            8590        1030
    ##  5        5        1.45                 15            7830        9950
    ##  6        6        1.71                 15            8210       10340
    ##  7        7        1.82                 15            9830       11020
    ##  8        8        2.37                 15            9240        8760
    ##  9        9        2.64                 15            9540        8810
    ## 10       10        2.78                 15            8230        7800
    ## # ℹ 96 more rows
    ## # ℹ 5 more variables: cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, homes_powered <dbl>

### Gwynnda

``` r
G_TW = read_excel("data/Trash_wheel.xlsx", sheet = "Gwynnda Trash Wheel",
                      col_types = c("numeric", "skip", "skip", "skip", "numeric", "numeric", "numeric", "numeric", "numeric","numeric", "numeric", "numeric")) |>
  janitor::clean_names() |>
  slice(1:(n()-2))
print(G_TW)
```

    ## # A tibble: 155 × 9
    ##    dumpster weight_tons volume_cubic_yards plastic_bottles polystyrene
    ##       <dbl>       <dbl>              <dbl>           <dbl>       <dbl>
    ##  1        1        0.93                 15            1200         360
    ##  2        2        2.26                 15            2000         240
    ##  3        3        1.62                 15            1800         270
    ##  4        4        1.76                 15            1000         180
    ##  5        5        1.53                 15            2100         240
    ##  6        6        2.06                 15            2400         360
    ##  7        7        1.9                  15            2700         320
    ##  8        8        2.16                 15            3000         320
    ##  9        9        2.6                  15             980         180
    ## 10       10        3.21                 15             240          42
    ## # ℹ 145 more rows
    ## # ℹ 4 more variables: cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>
